In [ ]:
!wget https://www.dropbox.com/s/f1x86l7xkdkz6ke/Admission_Predict.csv

--2023-02-09 04:18:52--  https://www.dropbox.com/s/f1x86l7xkdkz6ke/Admission_Predict.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:601c:18::a27d:612
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/f1x86l7xkdkz6ke/Admission_Predict.csv [following]
--2023-02-09 04:18:52--  https://www.dropbox.com/s/raw/f1x86l7xkdkz6ke/Admission_Predict.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9eb8f90b3f91e86482ab3a5dc8.dl.dropboxusercontent.com/cd/0/inline/B2LlAAjAdX38rJcPqCqbwkICdw2yQl9ldr7haBFE9jGfJMvdWWZNYcu0JBMgYu48YMQhU_TCQsqioGE9IKEiOXZNOcdiKZDfLb5kIxMjNEBL3Ck_c9Eihe0jDPJ5DvMGz3ybWiIe_Y0aY150caLEWlG1p5yH-lblW829lY3rGMaFwQ/file# [following]
--2023-02-09 04:18:52--  https://uc9eb8f90b3f91e86482ab3a5dc8.dl.dropboxusercontent.com/cd/0/inline/B2LlAAjAdX38rJcPqCqbwkICdw2yQl9ldr7haBFE9jGfJMvdWWZNY

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv('Admission_Predict.csv')
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76  
2         1             0.72  
3         1             0.80  
4         0             0.65

In [ ]:
df.shape

(500, 9)

In [ ]:
df.describe(include = 'all')

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.472000   107.192000           3.114000    3.374000   
std    144.481833   11.295148     6.081868           1.143512    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  308.000000   103.000000           2.000000    2.500000   
50%    250.500000  317.000000   107.000000           3.000000    3.500000   
75%    375.250000  325.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

            LOR         CGPA    Research  Chance of Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [ ]:
x = df['GRE Score']
y = df['Chance of Admit']

#Linear Regression hence statistical data. So convert to an array
x = np.array(x)
y = np.array(y)
x.shape, y.shape

((500,), (500,))

In [ ]:
x = x.reshape(-1, 1)
y = y.reshape(-1, 1)
x.shape, y.shape

((500, 1), (500, 1))

Scaling the data due to the gap between X and Y

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler1 = StandardScaler()
scaler2 = StandardScaler()

x = scaler1.fit_transform(x)
y = scaler2.fit_transform(y)

In [ ]:
x[0:5,0], y[0:5,0]

(array([ 1.81923762,  0.66714832, -0.0418297 ,  0.48990382, -0.21907421]),
 array([ 1.40610734,  0.27134907, -0.0123405 ,  0.55503864, -0.50879724]))

In [ ]:
from sklearn.model_selection import train_test_split

#Split to train and test data
#random values will be taken
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=1)
print(x_train.shape, y_train.shape, x_test.shape, x_test.shape)

(375, 1) (375, 1) (125, 1) (125, 1)


In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, accuracy_score

lr_model = LinearRegression()
lr_model.fit(x_train, y_train)
#model created and plot is done

LinearRegression()

In [ ]:
lr_model.coef_, lr_model.intercept_

(array([[0.80361256]]), array([0.02740836]))

In [ ]:
accuracy_lr = lr_model.score(x_test, y_test)
print('The accuracy is: ',accuracy_lr)

The accuracy is:  0.6260055317126939


Logistic Regression: Output comes under classes. KNN, SVM, DecisionTree, RandomForest